### ISSUE TITLE
Error executing Crowdstrike Install Powershell script

### ISSUE THREAD

**Issue by vitbyst** [CrowdStrike/Cloud-AWS#111] opened 2021-10-20 18:18 UTC
Trying to execute the Powershell referred in https://github.com/CrowdStrike/Cloud-AWS/tree/master/Agent-Install-Examples/powershell

The script itself gives an example to execute it with parameters as  
`PS>.\sensor_install.ps1 -BaseAddress <string> -ClientId <string> -ClientSecret <string>`

However the user data shows without flagging parameters:
`C:\Windows\Temp\sensor.ps1 FALCON_CLIENT_ID_HERE FALCON_CLIENT_SECRET_HERE`

Anyway, getting an error on execution (actual id and secret are replaced, of course):

```
PS C:\Users\Administrator> C:\Windows\Temp\sensor_install.ps1 -BaseAddress 'https://api.crowdstrike.com' -ClientId 'xxxxxxxxxxxxxxxxxxxxx' -ClientSecret 'xxxxxxxxxxxxxxxxxx'
Exception calling "OpenRead" with "1" argument(s): "The remote server returned an error: (403) Forbidden."
At C:\Windows\Temp\sensor_install.ps1:129 char:9
+         $Request = $Falcon.OpenRead($Path)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.IO.StreamReader.
At C:\Windows\Temp\sensor_install.ps1:130 char:19
+         $Stream = New-Object System.IO.StreamReader $Request
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Windows\Temp\sensor_install.ps1:131 char:9
+         $Output = $Stream.ReadToEnd()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Failed to match policy name 'platform_default'
At C:\Windows\Temp\sensor_install.ps1:214 char:9
+         throw $Message
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to match...atform_default':String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to match policy name 'platform_default'

PS C:\Users\Administrator>
```

**Comment by vitbyst** [comment] 2021-11-02 07:58
I am sorry, you keep saying "It was not designed with Amazon EC2 in mind." for the issue in the repo named Cloud-AWS with such examples as https://github.com/CrowdStrike/Cloud-AWS/tree/master/Agent-Install-Examples/powershell illustrating how to set the EC2 user data. it's just bizarre.
My Crowdstrike administrators confirmed that the sensor version is assigned to the default sensor update policy for Windows, and our API client has the appropriate permissions

**Comment by bk-cs** [comment] 2021-11-02 16:11
The script exists in this repo because someone asked for a script that was designed to install Falcon via PowerShell. It was written before this repo existed, and had nothing to do with AWS. 

It sounds like it worked for you as long as .NET existed on the machine and you had the proper permissions?

I can work to add someone additional checks to verify .NET is present before it's executed, which should help prevent issues in the future. Thank you for your feedback!

**Comment by vitbyst** [comment] 2021-11-02 18:54
`PS C:\Users\Administrator> Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

PS C:\Users\Administrator>`

**Comment by redhatrises** [comment] 2021-11-02 20:21
Reopening this until #116 is merged.

**Closed** 2021-11-02 22:22 UTC
Labels: bug
